// hasApiClient reports whether a platform has an API client in chat-api.ts'
// getAuth (cookie session or OpenAI key). Sub-agents route through the API only
// on these; others fall back to the tab-worker path. Keep in sync with
// background/chat-api.ts getAuth coverage.
// chatgpt excluded: getAuth can fetch an accessToken, but /backend-api/conversation
// requires a sentinel turnstile token generated by the page's SentinelSDK, which
// external scripts cannot drive — the API call always fails, so spawn_agent goes
// straight to the tab-worker path instead of wasting a failed round trip.
const API_CLIENT_PLATFORMS = new Set(['qwen', 'claude', 'openai'])

export function hasApiClient(platform: string): boolean {
  return API_CLIENT_PLATFORMS.has(platform)
}
